_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: ea3fc893-ec58-4db6-89aa-0862c4cf388e
name: 'Drush Site-Install'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/5901
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
